# Generated by Django 5.0.6 on 2024-06-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_product_category_code_product_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_name',
        ),
    ]
